import React from 'react';
import {courseDetails} from './courseDetails';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,ArrowUpRight} from 'lucide-react';
const studies={
 decisionlens:{title:'DecisionLens',subtitle:'What changes a prediction: and what could someone actually do?',label:'RESEARCH PROTOTYPE / GRADUATE-ADMISSIONS RECOURSE',image:'/assets/decisionlens.png',alt:'DecisionLens prototype interface',intro:'DecisionLens explores the distance between a model saying “no” and a person understanding what alternatives might be available. Graduate admissions provides the setting: an applicant-facing prototype for examining predictions, counterfactual suggestions, and the assumptions behind them.',methods:['Random forest classifier','DiCE genetic counterfactuals','Feature-cost weighting','Assumption-based causal scenarios','Applicant-facing interface'],sections:[['The question','A counterfactual can flip a prediction without describing an action that is practical, affordable, or institutionally meaningful. I wanted to examine how recourse changes when those considerations enter the picture.'],['What I built','The prototype combines a random forest with DiCE counterfactual generation. It compares a baseline with feature-cost-weighted alternatives, then applies downstream adjustments under manually specified graph scenarios. The interface presents a profile, a model response, and possible changes for the applicant to inspect.'],['How the modelling works','The inspected implementation uses a 100-tree random forest with maximum depth 6, a stratified train/test split, and five-fold cross-validation. The classification target comes from thresholding “Chance of Admit” at 0.75. A raw-to-scaled wrapper connects the model to DiCE’s genetic search.'],['Looking across applicant backgrounds','The implementation includes summaries across groups defined by university rating, CGPA bands, and research experience. These are exploratory comparisons of the model and recourse mechanism, rather than a demonstrated demographic fairness guarantee.'],['What the prototype cannot tell us','The dataset contains an admissions-chance proxy, not observed committee decisions. Action costs are assumed, and the graph scenarios are manually specified. A changed prediction therefore does not establish admission success, an identified causal effect, or globally minimum-cost action.'],['Why the distinction matters','An explanation should make the model’s reasoning and assumptions easier to examine. The broader question is whether it also helps the affected person assess the advice, challenge its premises, or recognize when the institution itself needs to change.']]},
 fairscore:{title:'FairScore',subtitle:'A risk score should open questions, not close them.',label:'ONGOING PROJECT / TRANSPARENT ALGORITHMIC RISK ASSESSMENT',intro:'FairScore investigates risk-scoring models alongside the tools used to explain and challenge them. The work combines predictive modelling, local and global explanations, counterfactual recourse, and examination of confounding and proxy discrimination.',methods:['Gradient-boosted trees','Ensemble models','SHAP','LIME','DiCE-ML','Causal analysis'],sections:[['The question','When a system assigns someone a risk score, what information lets another person meaningfully assess it? Predictive performance is one part of that question. Explanations, alternative inputs, confounding, and the context of use also matter.'],['The modelling layer','I built a risk-scoring system using gradient-boosted decision trees and ensemble methods for high-stakes behavioural data. The project remains ongoing; this overview describes the implemented approach rather than a validated deployment.'],['Explanations at two scales','SHAP and LIME are used to investigate model behaviour and support exploratory validation. Global patterns help identify recurring model tendencies, while local explanations make an individual prediction more open to inspection. Neither automatically establishes that a decision is justified.'],['Exploring alternatives','DiCE-ML counterfactuals communicate how different inputs could change the model’s prediction. This is a way to inspect model sensitivity and candidate recourse; practical feasibility still depends on the features, costs, constraints, and real-world decision process.'],['Confounding and proxy discrimination','The work includes causal analysis to investigate confounding and potential proxy discrimination in automated decision pipelines. These questions require care about what is observed, what is assumed, and what conclusions the available evidence supports.'],['Current limits and direction','I do not present this project as proof of discrimination-free decisions, demonstrated real-world recourse, or independent validation of a deployed system. The continuing aim is to make the scoring process and its assumptions easier to interrogate.']]}
};
export function CaseStudy(){const {project}=useParams(),p=studies[project];if(!p)return <div className="wrap empty"><h1>Project not found.</h1><Link to="/research">Return to research</Link></div>;return <div className="wrap case-study"><Link className="case-back" to="/research"><ArrowLeft size={15}/> Work & Research</Link><header className="page-heading"><span className="eyebrow">{p.label}</span><h1>{p.title}</h1><p className="case-subtitle">{p.subtitle}</p></header>{p.image?<figure className="case-image"><img src={p.image} alt={p.alt}/><figcaption>Research prototype interface</figcaption></figure>:<div className="fairscore-diagram" aria-label="FairScore research workflow"><span>01<em>Predict</em><small>Tree-based risk model</small></span><i>→</i><span>02<em>Examine</em><small>SHAP · LIME</small></span><i>→</i><span>03<em>Question</em><small>Recourse · causal assumptions</small></span></div>}<p className="case-intro">{p.intro}</p><div className="method-tags">{p.methods.map(m=><span key={m}>{m}</span>)}</div><div className="case-sections">{p.sections.map(([title,text],i)=><section key={title}><span className="eyebrow">0{i+1}</span><h2>{title}</h2><p>{text}</p></section>)}</div><section className="case-contact"><h2>Questions about the work?</h2><a href={'mailto:omanijabess47@gmail.com?subject='+encodeURIComponent(p.title+' research enquiry')} className="text-link">Discuss the project <ArrowUpRight size={17}/></a></section></div>;}

export const training=[
 {title:'Introduction to Agent-Based Modelling',provider:'UNU-MERIT / Maastricht University',year:'2026',type:'Professional development',topics:'Python, R, NetLogo; socioeconomic simulation, model validation and sensitivity analysis.'},
 {title:'ARENA learning materials',provider:'ARENA',year:'2026',type:'Independent study',topics:'Fundamentals, transformer interpretability, and LLM evaluations.'},
 {title:'ML Safety',provider:'ML Safety.org',year:'2026',type:'Online study',topics:'Robustness, monitoring, systemic risk, and safe deployment.'},
 {title:'AI Research Foundations',provider:'Google DeepMind learning pathway',year:'2025',type:'Online study',topics:'Neural networks, transformers, language modelling, fine-tuning and evaluation.'},
 {title:'Mathematics of Machine Learning Summer School',provider:'The Alan Turing Institute',year:'2025',type:'Online study',topics:'Supervised learning, stochastic optimization, generalization and statistical learning.'},
 {title:'Assessing and Mitigating Bias in AI',provider:'The Alan Turing Institute',year:'2025',type:'Online study',topics:'Fairness assessment and mitigation, including topics beyond binary classification.'},
 {title:'Machine Learning for Public Policy',provider:'UNU-MERIT / Maastricht University',year:'2025',type:'Professional development',topics:'ML methods, bias assessment, policy-focused evaluation and a collaborative policy challenge.'}
];
export function CourseHistory(){return <section className="course-history" id="courses"><span className="eyebrow">COURSES & CONTINUING STUDY</span><h2>Courses &amp;<br/><em>continuing study.</em></h2><p className="course-intro">Short summaries of the official programme descriptions, with links to the providers.</p><div className="learning-layers" aria-label="Areas of continuing study"><a href="#course-5">01 · Mathematical foundations</a><a href="#course-4">02 · Model engineering</a><a href="#course-3">03 · Safety & evaluation</a><a href="#course-7">04 · Policy & social systems</a></div><div className="course-list">{training.map((c,i)=>{const d=courseDetails[i];return <article key={c.title} id={'course-'+(i+1)}><span className="course-year">{c.year}</span><div><span className="eyebrow">{d.type||c.type}</span><h3>{d.title||c.title}</h3><p className="course-provider">{c.provider}</p><p>{d.coverage}</p><div className="course-sources">{d.sources.map(([label,url])=><a href={url} key={url} target="_blank" rel="noopener noreferrer">{label} <ArrowUpRight size={13}/></a>)}</div></div><span className="course-index">0{i+1}</span></article>})}</div><div className="degree-coursework"><h3>Undergraduate coursework</h3><p>BTech Mechatronics Engineering · Koforidua Technical University · 2021–2024</p><div className="method-tags">{['Calculus','Computer Programming','Control Systems','Embedded Systems','Digital Signal & Image Processing','Robotics','Research Methods'].map(c=><span key={c}>{c}</span>)}</div></div><p className="course-note">Descriptions are shortened paraphrases of the linked official pages, checked on 20 September 2026. Years indicate my study dates; independent study is not presented as certification.</p></section>;}
