export const sections=[
 {id:'all',name:'The whole journal',short:'All writing'},
 {id:'politics',name:'Politics & Public Life',short:'Public life',number:'01',color:'#cf714f',symbol:'↗',purpose:'Thinking through power, institutions, and the decisions we make together. A place to question what is presented as inevitable: and whose interests it serves.'},
 {id:'ai',name:'AI Safety & Society',short:'AI & society',number:'02',color:'#889687',symbol:'◎',purpose:'What happens when increasingly capable systems meet imperfect institutions? On evidence, accountability, governance, and the people living with the consequences.'},
 {id:'personal',name:'Personal Thoughts',short:'Personal thoughts',number:'03',color:'#b6a488',symbol:'✳',purpose:'Things I am learning, wrestling with, or not yet ready to resolve. On ambition, uncertainty, relationships, and becoming.'},
 {id:'drill',name:'Seven-Minute Drill',short:'7-minute drill',number:'04',color:'#d5b85c',symbol:'07',purpose:'Seven minutes. Whatever is on my mind or in my heart. A practice in writing before doubt takes over, building confidence, and learning to trust my pen.'},
 {id:'commentary',name:'Commentary',short:'Commentary',number:'05',color:'#a3a5b7',symbol:'“',purpose:'A conversation with something someone else has made, said, or lived. Music, art, lectures, history, and the ideas that stay with me.'}
];
export const commentaryTypes=['Music & Lyrics','Art','Talks & Lectures','History','People & Lives','First-person Accounts'];
export const projects=[{title:'DecisionLens',type:'Research prototype',desc:'When a prediction changes, what has actually become possible?',detail:'A graduate-admissions recourse prototype combining random forests, DiCE counterfactuals, feature costs and manually specified causal scenarios. Its target is an admissions-chance proxy, not observed committee decisions. It explores recommendations and their assumptions; it does not establish real admissions outcomes or causal effects.',image:'/assets/decisionlens.png',tags:'Interpretability · Counterfactual recourse'}, {title:'FairScore',type:'Ongoing applied research',desc:'Making risk predictions open to examination.',detail:'A risk-scoring project using tree-based models, SHAP, LIME and counterfactual explanations to examine model behaviour and the assumptions behind automated decisions.',tags:'Model evaluation · Explainability'}, {title:'HexAI',type:'Collaborative project',desc:'Accessible interaction starts with listening.',detail:'A Ghanaian Sign Language project. My contribution includes coordination between deaf and hard-of-hearing communities and software, AI and design teams, data-card preparation, and technical work.',tags:'Accessibility · Community participation'}];
export const milestones=[{date:'Current',title:'Associate Editor · Spider Publishing',text:'Editorial work alongside my research and writing practice.'},{date:'2026',title:'Ambassador · Thinking About Thinking',text:'Interdisciplinary engagement connecting AI, neuroscience, cognitive science and human-centred system design.'},{date:'2026',title:'AI safety, in conversation',text:'Speaker, PyTorch Community East Africa: AI Safety: Building Safer and More Responsible AI Systems.',url:'https://luma.com/ea1ozt18'}, {date:'2026',title:'Ghana Internet Governance Fellow',text:'Engaging with digital policy, internet governance and responsible technology.'}, {date:'2025: ',title:'AI Research Engineer · Mingo Blox',text:'Applied research and prototyping, with attention to explainability, safety and usability.'}, {date:'2024',title:'BTech, Mechatronics Engineering',text:'First Class Honours · Koforidua Technical University.'}];
export const plain=html=>(html||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ');
export const reading=html=>Math.max(1,Math.ceil(plain(html).split(/\s+/).filter(Boolean).length/220));
export const safeUrl=url=>{try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};
export const emptyDraft=section=>({title:'',body:'',excerpt:'',section:section||'personal',format:section==='drill'?'Seven-minute drill':'Essay',subtype:'',tags:'',cover:'',coverAlt:'',sourceUrl:'',sourceTitle:'',sourceCreator:'',sourceNote:'',featured:false,writingSample:false,revision:0});
