export const sections=[
 {id:'all',name:'The whole journal',short:'All writing'},
 {id:'politics',name:'Politics & Public Life',short:'Public life',number:'01',color:'#cf714f',symbol:'↗',purpose:'Thinking through power, institutions, and the decisions we make together. A place to question what is presented as inevitable: and whose interests it serves.'},
 {id:'ai',name:'AI Safety & Society',short:'AI & society',number:'02',color:'#889687',symbol:'◎',purpose:'What happens when increasingly capable systems meet imperfect institutions? On evidence, accountability, governance, and the people living with the consequences.'},
 {id:'personal',name:'Personal Thoughts',short:'Personal thoughts',number:'03',color:'#b6a488',symbol:'✳',purpose:'Things I am learning, wrestling with, or not yet ready to resolve. On ambition, uncertainty, relationships, and becoming.'},
 {id:'drill',name:'Seven-Minute Drill',short:'7-minute drill',number:'04',color:'#d5b85c',symbol:'07',purpose:'Seven minutes. Whatever is on my mind or in my heart. A practice in writing before doubt takes over, building confidence, and learning to trust my pen.'},
 {id:'commentary',name:'Commentary',short:'Commentary',number:'05',color:'#a3a5b7',symbol:'“',purpose:'A conversation with something someone else has made, said, or lived. Music, art, lectures, history, and the ideas that stay with me.'}
];
export const commentaryTypes=['Music & Lyrics','Art','Talks & Lectures','History','People & Lives','First-person Accounts'];
export const projects=[{"title":"HexAI","image":"/assets/ghanaian-sign-language.jpg","imageAlt":"A person demonstrating the sign for school in Ghanaian Sign Language","type":"Machine-learning engineer · Ongoing","desc":"Bidirectional Ghanaian Sign Language translation.","detail":"A collaborative AI project developing accessible interaction through Ghanaian Sign Language translation. I built HexAI as the machine-learning engineer, contributing to the bidirectional translation system alongside software and design colleagues. My work also included dataset documentation and collaboration with deaf and hard-of-hearing communities.","tags":"Sign-language AI · Dataset documentation · Accessible interaction"},{"title":"DecisionLens","type":"Machine learning & algorithmic recourse","desc":"From an admissions prediction to cost-aware alternatives.","detail":"An applicant-facing decision-support system combining a random forest classifier with DiCE’s genetic counterfactual search. It compares alternative profiles using feature-cost weights and graph-based scenarios, with cross-validation and analysis across applicant backgrounds.","image":"/assets/decisionlens.png","tags":"Random forests · DiCE · Cost-aware recourse · Model evaluation"},{"title":"FairScore","type":"Applied ML research · Ongoing","desc":"Risk modelling with explanations and counterfactual analysis.","detail":"A risk-scoring system combining gradient-boosted trees and ensemble methods with SHAP, LIME and DiCE-ML. The work integrates predictive modelling, local and global explanations, and analysis of confounding and proxy discrimination in automated decision pipelines.","tags":"Gradient boosting · SHAP · LIME · DiCE-ML"}];
export const milestones=[{date:'Current',title:'Associate Editor · Spider Publishing',text:'Editorial work alongside my research and writing practice.'},{date:'2026',title:'Ambassador · Thinking About Thinking',text:'Interdisciplinary engagement connecting AI, neuroscience, cognitive science and human-centred system design.'},{date:'2026',title:'AI safety, in conversation',text:'Speaker, PyTorch Community East Africa: AI Safety: Building Safer and More Responsible AI Systems.',url:'https://luma.com/ea1ozt18'}, {date:'2026',title:'Ghana Internet Governance Fellow',text:'Engaging with digital policy, internet governance and responsible technology.'}, {date:'2025 to present',title:'AI Research Engineer · Mingo Blox',text:'Applied research and prototyping, with attention to explainability, safety and usability.'}, {date:'2024',title:'BTech, Mechatronics Engineering',text:'First Class Honours · Koforidua Technical University.'}];
export const plain=html=>(html||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ');
export const reading=html=>Math.max(1,Math.ceil(plain(html).split(/\s+/).filter(Boolean).length/220));
export const safeUrl=url=>{try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};
export const emptyDraft=section=>({title:'',body:'',excerpt:'',section:section||'personal',format:section==='drill'?'Seven-minute drill':'Essay',subtype:'',tags:'',cover:'',coverAlt:'',sourceUrl:'',sourceTitle:'',sourceCreator:'',sourceNote:'',featured:false,writingSample:false,revision:0});
