import React, {useState, useEffect} from 'react';
import {Link} from 'react-router-dom';
import {ArrowLeft, ArrowUpRight, Phone, PhoneOff, Volume2, ShieldCheck, Signal, Users, Globe2, ArrowRight, RotateCcw} from 'lucide-react';
import knowledge from './kasa-knowledge.json';
import {retrieveAnswer} from './kasa-retrieval.mjs';
import './kasa.css';

const languages = {twi:'Twi', hausa:'Hausa', pidgin:'Pidgin', en:'English'};
const greetings = {twi:'Akwaaba. Me din de Kasa AI. Mɛboa wo sɛn?', hausa:'Sannu. Ni ne Kasa AI. Ta yaya zan taimaka maka?', pidgin:'Akwaaba! I be Kasa AI. How I fit help you today?', en:'Welcome. I am Kasa AI, your automated support assistant. How can I help?'};
const questions = {
  twi:['Me data nyɛ adwuma.', 'Mepɛ sɛ mehwɛ me airtime.', 'Mepɛ adwumayɛni.', 'Ɔkyena osu bɛtɔ?'],
  hausa:['Data ba ya aiki.', 'Ina son duba airtime.', 'Ina son magana da mutum.', 'Za a yi ruwan sama gobe?'],
  pidgin:['My data no dey work.', 'Help me check my airtime.', 'I wan talk to a person.', 'Rain go fall tomorrow?'],
  en:['My data is not working.', 'Help me check my airtime.', 'I want a human agent.', 'Will it rain tomorrow?']
};
const labels = ['Data not working', 'Check airtime', 'Speak to a person', 'Ask outside the knowledge base'];
const contact = 'mailto:omanijabess47@gmail.com?subject=Kasa%20AI%20pilot%20enquiry';

export default function KasaAI(){
  const [language,setLanguage]=useState('twi'), [channel,setChannel]=useState('voice');
  const [connected,setConnected]=useState(false), [messages,setMessages]=useState([]), [question,setQuestion]=useState('');
  const [result,setResult]=useState(null), [consent,setConsent]=useState(false), [summary,setSummary]=useState(false), [audioNote,setAudioNote]=useState('');
  useEffect(()=>()=>{window.speechSynthesis?.cancel();},[]);
  function reset(){window.speechSynthesis?.cancel();setConnected(false);setMessages([]);setResult(null);setQuestion('');setConsent(false);setSummary(false);setAudioNote('');}
  function start(){setConnected(true);setMessages([{role:'Kasa AI',text:greetings[language]}]);setResult(null);setSummary(false);}
  function ask(text){if(!text.trim())return;const answer=retrieveAnswer(knowledge,text,language);setMessages(m=>[...m.slice(-7),{role:'You',text},{role:'Kasa AI',text:answer.answer}]);setResult(answer);setQuestion('');setSummary(false);setConsent(false);}
  function listen(){
    if(!('speechSynthesis' in window)){setAudioNote('Audio preview is unavailable in this browser. The transcript is available below.');return;}
    const voice=window.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith('en'));
    if(!voice){setAudioNote('No English preview voice is installed. Read the transcript below.');return;}
    window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(result?.english||greetings.en);speech.voice=voice;speech.rate=.9;
    speech.onerror=()=>setAudioNote('Audio could not play. The transcript remains available.');window.speechSynthesis.speak(speech);
    setAudioNote('English browser voice preview. A Ghanaian Twi voice is part of the production integration, not this browser sample.');
  }
  return <div className="kasa-page">
    <div className="wrap kasa-top"><Link className="case-back" to="/research"><ArrowLeft size={15}/> Work & Research</Link><span>BUILT BY JABESS OMANE · GHANA</span></div>
    <section className="wrap kasa-hero">
      <div><span className="kasa-kicker"><i/> KASA AI / AI WITHOUT INTERNET ON YOUR PHONE</span><h1>Good support.<br/>In your <em>own<br/>language.</em></h1><p>No internet. No app to learn. Just call. Kasa AI brings personalised, multilingual customer care to people that apps and English-only menus leave behind—through the basic phone already in their hand.</p><div className="kasa-actions"><a href="#kasa-demo" className="kasa-button">Try the experience <ArrowUpRight size={18}/></a><a href={contact} className="kasa-secondary">Discuss a pilot <ArrowRight size={16}/></a></div><div className="kasa-languages">TWI <span>•</span> HAUSA <span>•</span> PIDGIN</div></div>
      <div className="kasa-hero-art" aria-label="Illustration of a basic phone connecting a caller to Kasa AI"><div className="kasa-orbit one"/><div className="kasa-orbit two"/><div className="kasa-art-note">NO APP.<br/>NO MOBILE DATA.<br/><strong>JUST A CONVERSATION.</strong></div><div className="kasa-phone"><div className="kasa-speaker"/><div className="kasa-screen"><span><Signal size={15}/> KASA AI</span><Phone size={24}/><strong>Akwaaba.</strong><small>Welcome. You belong here.</small><div className="kasa-wave" aria-hidden="true">{Array.from({length:19},(_,i)=><i key={i} style={{height:12+Math.sin(i*1.8)**2*30+'px'}}/>)}</div><small>Voice-first customer support</small></div><div className="kasa-keypad" aria-hidden="true">{['1','2','3','4','5','6','7','8','9','*','0','#'].map(k=><span key={k}>{k}</span>)}</div></div><div className="kasa-art-caption">Designed for the phone already in your hand.</div></div>
    </section>
    <div className="kasa-strip"><span><Phone size={18}/> Basic-phone access</span><span><Globe2 size={18}/> Familiar languages</span><span><ShieldCheck size={18}/> Source-backed answers</span><span><Users size={18}/> People when needed</span></div>
    <section className="wrap kasa-story"><span className="kasa-kicker">01 / THE REASON TO BUILD</span><div><h2>For my mum.<br/><em>And everyone like her.</em></h2><p>My mum should not have to read an app, buy mobile data, or explain herself in English to get help. She should be able to call, speak Twi, and be understood.</p><p>That is the starting point for Kasa AI: customer service designed around the person asking for help. Direct voice calling serves people who cannot read. USSD offers a simple callback route for those comfortable with short menus.</p></div></section>
    <section className="kasa-demo-section" id="kasa-demo"><div className="wrap"><header className="kasa-section-heading"><div><span className="kasa-kicker">02 / EXPERIENCE KASA</span><h2>A small call.<br/><em>A different kind of access.</em></h2></div><p>Explore a working browser demo. Choose a language, start a simulated call, and see the exact knowledge source behind each supported answer.</p></header>
      <div className="kasa-demo-layout"><div className="kasa-console"><div className="kasa-console-top"><strong>Kasa AI</strong><span><i/>{connected?'Demo session active':'Interactive demo'}</span></div><div className="kasa-controls"><label>Conversation language<select value={language} onChange={e=>{reset();setLanguage(e.target.value);}}>{Object.entries(languages).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><fieldset><legend>How you connect</legend><button aria-pressed={channel==='voice'} onClick={()=>{reset();setChannel('voice');}}>Voice call</button><button aria-pressed={channel==='ussd'} onClick={()=>{reset();setChannel('ussd');}}>USSD callback</button></fieldset></div>
      {!connected?<div className="kasa-start"><Phone size={32}/><h3>{channel==='voice'?'A familiar voice is one call away.':'A short menu. Then a voice.'}</h3><p>{channel==='voice'?'In a deployment, dial your provider’s support number and speak in your language.':'In a deployment, a USSD menu lets you request a callback. The conversation continues by voice.'}</p>{channel==='ussd'&&<div className="kasa-ussd">Kasa AI support<br/>1. Request a callback<br/>0. Exit</div>}<button className="kasa-button" onClick={start}>{channel==='voice'?'Start demo call':'1 · Simulate callback'} <Phone size={16}/></button><small>Simulation only. No phone number or mobile account is connected.</small></div>:<><div className="kasa-transcript" role="log" aria-label="Conversation transcript" aria-live="polite">{messages.map((m,i)=><div key={i} className={m.role==='You'?'kasa-message caller':'kasa-message'}><small>{m.role}</small><p>{m.text}</p></div>)}</div><div className="kasa-prompts">{questions[language].map((q,i)=><button key={q} onClick={()=>ask(q)} title={q}>{labels[i]} <ArrowUpRight size={12}/></button>)}</div><form className="kasa-question" onSubmit={e=>{e.preventDefault();ask(question);}}><label htmlFor="kasa-question">Or type a support question</label><div><input id="kasa-question" value={question} maxLength={500} placeholder="Ask about data, airtime, or human support…" onChange={e=>setQuestion(e.target.value)}/><button type="submit" disabled={!question.trim()} aria-label="Send question"><ArrowRight size={20}/></button></div></form><div className="kasa-session-actions"><button onClick={listen}><Volume2 size={15}/> English audio preview</button><button onClick={reset}><PhoneOff size={15}/> End call</button></div>{audioNote&&<p className="kasa-small" role="status">{audioNote}</p>}</>}
      </div><aside className="kasa-evidence"><span className="kasa-kicker">BEHIND THE CONVERSATION</span><h3>Answers with<br/><em>something behind them.</em></h3><ol className="kasa-flow"><li><b>01</b><div><strong>Understand the request</strong><p>Recognise the caller’s language and support need.</p></div></li><li><b>02</b><div><strong>Find the approved answer</strong><p>Retrieve relevant information from the organisation’s knowledge base.</p></div></li><li><b>03</b><div><strong>Reply—or bring in a person</strong><p>Use a supported answer. Escalate when the source is missing or the issue needs a human.</p></div></li></ol><div className="kasa-source" aria-live="polite"><span className="kasa-kicker">{result?'RETRIEVAL RESULT':'WAITING FOR YOUR QUESTION'}</span>{result?<><h4>{result.source?.title||'No supported answer'}</h4><p>{result.source?`${result.source.id} · ${result.source.section}`:result.reason}</p><span className="kasa-status">{result.handoff?'Human support suggested':'Answer found in demo knowledge base'}</span>{language!=='en'&&<details><summary>English meaning</summary><p>{result.english}</p></details>}</>:<p>Ask a question to inspect its source. Try the weather question to see Kasa decline an unsupported answer.</p>}</div>{result?.handoff&&<div className="kasa-handoff"><label><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);setSummary(false);}}/> Include this conversation in the demo handoff summary</label><button className="kasa-button" disabled={!consent} onClick={()=>setSummary(true)}>Preview handoff</button>{summary&&<div role="status"><strong>Demo handoff prepared</strong><p>Language: {languages[language]} · Channel: {channel==='voice'?'Voice call':'USSD callback'}</p><p>Latest question: {messages.filter(m=>m.role==='You').at(-1)?.text}</p><p>Reason: {result.reason}. Nothing has been sent; no live agent is connected.</p></div>}</div>}<button className="kasa-reset" onClick={reset}><RotateCcw size={14}/> Reset experience</button></aside></div>
      <p className="kasa-demo-note">This demo retrieves prewritten answers locally from fictional service policies; it does not run a generative model or place real calls. Language samples are illustrative and need native-speaker validation. No MTN partnership or ownership of a support number such as 200 is implied.</p>
    </div></section>
    <section className="wrap kasa-benefits"><span className="kasa-kicker">03 / BETTER ACCESS. A LIGHTER WORKLOAD.</span><h2>Let your customers talk.<br/><em>Let your team breathe.</em></h2><div className="kasa-benefit-grid"><article><span>01 / INCLUSION</span><h3>Meet people<br/>where they are.</h3><p>Make support approachable in Twi, Hausa and Pidgin, through the basic phones people already use. Voice access removes the need to read a screen.</p></article><article><span>02 / SUPPORT TEAMS</span><h3>Less repetition.<br/>More meaningful help.</h3><p>Handle routine questions with consistent information, so agents can focus on complex cases and the conversations that need human care. Designed to ease the pressure that contributes to burnout.</p></article><article><span>03 / ALWAYS AVAILABLE</span><h3>Help beyond<br/>office hours.</h3><p>Designed for 24/7 automated first-line support. Capture unresolved requests after hours and pass context to your team when they are available.</p></article></div></section>
    <section className="wrap kasa-innovation"><div><span className="kasa-kicker">04 / THE INNOVATION</span><h2>The intelligence<br/>is in <em>the access.</em></h2></div><div><details open><summary>No internet on the caller’s device</summary><p>The caller uses a normal cellular voice connection or USSD. Language processing runs on the service side. Offline-first processing can run close to the telephony gateway; cellular coverage and an operating service are still required.</p></details><details><summary>A voice that feels like home</summary><p>The production goal is fluent Twi with a natural Ghanaian voice, alongside Hausa and Pidgin. This needs speech models, representative evaluation, and native speakers involved in testing—not just translated menus.</p></details><details><summary>Knowledge-grounded support</summary><p>The RAG design retrieves approved company knowledge before composing an answer. Source checks, abstention and human escalation reduce unsupported answers. RAG alone does not eliminate hallucinations. This demo uses extractive retrieval: its answers are returned directly from its small knowledge base.</p></details><details><summary>Built around a human handoff</summary><p>When a question falls outside approved knowledge, Kasa should say so. A consent-based summary gives the next agent context without making the customer start again. Actual transfers require the organisation’s call-centre integration.</p></details></div></section>
    <section className="wrap kasa-benefits kasa-trust"><span className="kasa-kicker">05 / PERSONAL BY DESIGN. CAREFUL WITH YOUR DATA.</span><h2>Know the person.<br/><em>Respect their privacy.</em></h2><div className="kasa-benefit-grid"><article><span>PERSONALISATION</span><h3>Your language.<br/>Your conversation.</h3><p>The demo adapts to your chosen language and keeps the conversation together during your visit. The live-service design adds consent-based language preferences and verified account context, so support can pick up where you left off.</p></article><article><span>PRIVACY IN THIS DEMO</span><h3>Try it without<br/>giving anything away.</h3><p>No sign-up, phone number or microphone permission is required. Typed demo questions stay in the page’s memory; they are not sent to a support server. Reset clears the session. Handoff summaries appear only with your permission.</p></article><article><span>SECURITY ARCHITECTURE</span><h3>Care with access.<br/>Control over actions.</h3><p>The backend includes policy checks, scoped tool execution and audit-event foundations. A live pilot needs verified identity for account actions, authenticated telephony, encryption, retention controls and security testing before handling customer data.</p></article></div></section>
    <section className="wrap kasa-delivery"><span className="kasa-kicker">PRODUCT / DELIVERY STATUS</span><p><strong>Working today:</strong> interactive multilingual demo, offline local knowledge retrieval, source display, unsupported-question fallback and consent-based handoff preview. Once loaded, its text experience needs no network requests. The backend includes telephony adapters and a speech pipeline.</p><p><strong>For a live pilot:</strong> connect an authorised phone number or shortcode, supply approved business knowledge, integrate validated speech models, and test calling, language quality, security and agent transfers with real users. Offline access means no mobile internet on the caller’s device; voice and USSD still need cellular coverage.</p></section>
    <section className="kasa-cta"><div className="wrap"><span className="kasa-kicker">FOR TELCOS, UTILITIES & CUSTOMER SERVICE TEAMS</span><h2>Your next customer<br/>may never download your app.<br/><em>Be there when they call.</em></h2><a href={contact} className="kasa-button">Let’s discuss Kasa AI <ArrowUpRight size={18}/></a><p>Start with one language, one support journey, and a pilot that measures access, resolution and customer experience.</p></div></section>
  </div>;
}
