import React, {useState, useEffect} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight, Phone, PhoneOff, Volume2, ShieldCheck, Signal, Users, Globe2, ArrowRight, RotateCcw} from 'lucide-react';
import knowledge from './kasa-knowledge.json';
import {retrieveAnswer} from './kasa-retrieval.mjs';
import './kasa.css';

const languages = {twi:'Twi', hausa:'Hausa', pidgin:'Pidgin', en:'English'};
const greetings = {twi:'Akwaaba. Me din de Kasa AI. Mɛboa wo sɛn?', hausa:'Sannu. Ni ne Kasa AI. Ta yaya zan taimaka maka?', pidgin:'Akwaaba! I be Kasa AI. How I fit help you today?', en:'Welcome. I am Kasa AI, your automated support assistant. How can I help?'};
const questions = {
  twi:['Me data nyɛ adwuma.', 'Mepɛ sɛ mehwɛ me airtime.', 'Mepɛ adwumayɛni.', 'Ɔkyena osu bɛtɔ?'],
  hausa:['Data ba ya aiki.', 'Ina son duba airtime.', 'Ina son magana da mutum.', 'Za a yi ruwan sama gobe?'],
  pidgin:['My data no dey work.', 'Help me check my airtime.', 'I wan talk to a person.', 'Rain go fall tomorrow?'],
  en:['My data is not working.', 'Help me check my airtime.', 'I want a human agent.', 'Will it rain tomorrow?']
};
const labels = ['Data not working', 'Check airtime', 'Speak to a person', 'Ask outside the knowledge base'];
const contact = 'mailto:omanijabess47@gmail.com?subject=Kasa%20AI%20pilot%20enquiry';

export default function KasaAI(){
  const [language,setLanguage]=useState('twi'), [channel,setChannel]=useState('voice');
  const [connected,setConnected]=useState(false), [messages,setMessages]=useState([]), [question,setQuestion]=useState('');
  const [result,setResult]=useState(null), [consent,setConsent]=useState(false), [summary,setSummary]=useState(false), [audioNote,setAudioNote]=useState('');
  useEffect(()=>()=>{window.speechSynthesis?.cancel();},[]);
  useEffect(()=>{const title=document.title;document.title='Kasa AI | Customer care without the waiting game';return()=>{document.title=title;};},[]);
  function reset(){window.speechSynthesis?.cancel();setConnected(false);setMessages([]);setResult(null);setQuestion('');setConsent(false);setSummary(false);setAudioNote('');}
  function start(){setConnected(true);setMessages([{role:'Kasa AI',text:greetings[language]}]);setResult(null);setSummary(false);}
  function ask(text){if(!text.trim())return;const answer=retrieveAnswer(knowledge,text,language);setMessages(m=>[...m.slice(-7),{role:'You',text},{role:'Kasa AI',text:answer.answer}]);setResult(answer);setQuestion('');setSummary(false);setConsent(false);}
  function listen(){
    if(!('speechSynthesis' in window)){setAudioNote('Audio preview is unavailable in this browser. The transcript is available below.');return;}
    const voice=window.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith('en'));
    if(!voice){setAudioNote('No English preview voice is installed. Read the transcript below.');return;}
    window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(result?.english||greetings.en);speech.voice=voice;speech.rate=.9;
    speech.onerror=()=>setAudioNote('Audio could not play. The transcript remains available.');window.speechSynthesis.speak(speech);
    setAudioNote('English browser voice preview. A Ghanaian Twi voice is part of the production integration, not this browser sample.');
  }
  return <div className="kasa-page">
    <header className="kb-nav"><a href="#" className="kb-brand" aria-label="Kasa AI home"><span className="kb-logo" aria-hidden="true"><i/><i/><i/><i/></span>kasa<span className="kb-ai">AI</span></a><nav aria-label="Kasa AI navigation"><a href="#why-kasa">Why Kasa</a><a href="#kasa-solutions">Solutions</a><a href="#kasa-demo">Try the demo</a></nav><a href={contact} className="kasa-button kb-nav-cta">Let’s talk <ArrowUpRight size={16}/></a></header>
    <section className="kb-hero kb-container"><div className="kb-hero-copy"><span className="kasa-kicker"><i/> CUSTOMER CARE. WITHOUT THE WAITING GAME.</span><h1>Your customers<br/>have a life.<br/><span>Don’t put it<br/>on hold.</span></h1><p>Meet Kasa AI. Personalised voice support in familiar languages, on the phones your customers already own. <strong>No app. No mobile internet. Just a call.</strong></p><div className="kasa-actions"><a className="kasa-button" href={contact}>Bring Kasa to your business <ArrowUpRight size={18}/></a><a className="kasa-secondary" href="#kasa-demo"><span className="kb-play">▶</span> Experience Kasa</a></div><div className="kb-hero-foot"><span className="kb-dot"/> Built for Ghana. Designed around people.</div></div><div className="kb-hero-visual"><img src="/assets/kasa-customer-hero.png" alt="Illustrative portrait of a Ghanaian customer enjoying a phone conversation" fetchPriority="high"/><div className="kb-photo-label">A familiar voice.<br/><strong>A better experience.</strong></div><div className="kb-call-card"><span className="kb-call-icon"><Phone size={21}/></span><div><strong>Akwaaba. How can I help?</strong><small>KASA AI · VOICE SUPPORT</small></div><div className="kb-audio" aria-hidden="true">{[14,26,18,34,23,13].map((n,i)=><i key={i} style={{height:n}}/>)}</div></div><span className="kb-photo-credit">AI-created campaign illustration</span></div></section>
    <section className="kb-value-strip kb-container" aria-label="Kasa AI advantages"><div><strong>24/7</strong><span>Designed for round-the-clock care</span></div><div><strong>Your language.</strong><span>Twi · Hausa · Pidgin</span></div><div><strong>No mobile data.</strong><span>AI access through a basic phone</span></div><div><strong>Personal by design.</strong><span>Context, care and consent</span></div></section>
    <section className="kb-pain-intro kb-container" id="why-kasa"><span className="kasa-kicker">YOU KNOW THE FEELING.</span><h2>“Your call is important to us.”<br/><span>Then why does nobody answer?</span></h2><p>Behind every call in a queue is someone trying to get on with their day. A payment. A match. A simple question. For them, it cannot wait.</p><span className="kb-scenario-note">Three everyday scenarios. One better way to respond.</span></section>
    <section className="kb-stories kb-container" id="kasa-solutions">
      <article className="kb-story"><div className="kb-scene kb-bank"><span className="kb-scene-label">01 / BANKING & FINANCIAL SERVICES</span><div className="kb-bank-slip"><span>TRANSFER STATUS</span><div className="kb-transfer-icon">↗</div><strong>Debited.<br/>Not received.</strong><p>Your money has left.<br/>Your answer hasn’t arrived.</p><div><span className="kb-pulse"/> Awaiting support</div></div><div className="kb-hold"><Phone size={19}/><span>Still on hold</span><strong>47:32</strong></div></div><div className="kb-story-copy"><span className="kasa-kicker">THE MONEY HAS GONE. THE WORRY HASN’T.</span><h2>A failed transfer.<br/>An hour you<br/><span>cannot get back.</span></h2><p>You send money. Your account is debited, but the recipient has nothing. You call the bank. Thirty minutes becomes an hour. Every minute of hold music makes the uncertainty worse.</p><div className="kb-solution"><span className="kb-mini-logo">k.</span><div><strong>With Kasa, the conversation starts.</strong><p>Kasa’s workflow captures the issue in the customer’s language, explains approved next steps, and prepares a clear escalation. With verified account integration, it can retrieve transaction status—without asking an agent to start from scratch.</p></div></div><a href={contact} className="kb-text-link">Build a calmer banking experience <ArrowUpRight size={16}/></a></div></article>
      <article className="kb-story kb-story-reverse"><div className="kb-scene kb-football"><span className="kb-scene-label">02 / PAY TV & SUBSCRIPTIONS</span><div className="kb-tv"><div className="kb-score">LIVE <i/> 68:14</div><div className="kb-pitch"><div/><span/></div><div className="kb-tv-message"><span>!</span><strong>Subscription not active</strong><small>But you have already paid.</small></div></div><div className="kb-match-caption">The match won’t wait.<br/><strong>Your support shouldn’t either.</strong></div></div><div className="kb-story-copy"><span className="kasa-kicker">YOU PAID FOR THE GAME. YOU’RE WATCHING A QUEUE.</span><h2>It’s match day.<br/>Your screen is blank.<br/><span>The game is live.</span></h2><p>You renew your football subscription. Friends arrive. Kick-off comes and goes, but your screen still says “not active”. Customer care is busy. You hear the neighbours celebrating a goal you paid to see.</p><div className="kb-solution"><span className="kb-mini-logo">k.</span><div><strong>Make the next step clear, while it matters.</strong><p>Kasa guides the customer through approved activation checks. Connected to your subscription system, it can check payment and activation status, then route unresolved cases with the right context.</p></div></div><a href={contact} className="kb-text-link">Keep the experience worth paying for <ArrowUpRight size={16}/></a></div></article>
      <article className="kb-story"><div className="kb-scene kb-access"><span className="kb-scene-label">03 / TELECOMS & EVERYDAY ESSENTIALS</span><div className="kb-language-cloud"><span>Hello.</span><span>Sannu.</span><strong>Akwaaba.</strong><span>How you dey?</span></div><div className="kb-access-call"><Phone size={27}/><div><strong>No app to download.</strong><span>No English required.</span><span>No mobile data needed.</span></div></div><div className="kb-language-tags"><span>Twi</span><span>Hausa</span><span>Pidgin</span></div></div><div className="kb-story-copy"><span className="kasa-kicker">SHE NEEDS HELP. NOT ANOTHER APP.</span><h2>Her phone is basic.<br/>Her language is Twi.<br/><span>Her needs matter.</span></h2><p>A market trader’s airtime disappears. The support menu is in English. The alternative is an app she cannot use. She asks someone else to make the call—or gives up entirely.</p><div className="kb-solution"><span className="kb-mini-logo">k.</span><div><strong>Let her speak for herself.</strong><p>Kasa is designed to meet her with a familiar Ghanaian voice. She calls and speaks in her language. Voice access removes the reading barrier; USSD offers a callback option. No smartphone skills or internet bundle required.</p></div></div><a href={contact} className="kb-text-link">Make inclusion part of your service <ArrowUpRight size={16}/></a></div></article>
    </section>
    <section className="kb-business"><div className="kb-container"><div className="kb-business-heading"><span className="kasa-kicker">BETTER FOR CUSTOMERS. BETTER FOR YOUR TEAM.</span><h2>Every repeat question<br/>takes time from a<br/><span>conversation that needs a person.</span></h2><p>Give routine support to Kasa. Give your people the space to handle the difficult, sensitive and human moments well.</p></div><div className="kb-benefit-grid"><article><Users/><h3>Less pressure.<br/>More capacity.</h3><p>Reduce repetitive first-line work and the pressure that feeds agent burnout. Send complex cases onward with context.</p></article><article><Globe2/><h3>Personalisation<br/>that feels natural.</h3><p>Start with the customer’s language. Add consent-based preferences and verified account context through your business integrations.</p></article><article><Phone/><h3>Support beyond<br/>business hours.</h3><p>Design for 24/7 first-line care. Answer approved questions and capture requests even when your human team is offline.</p></article></div></div></section>
    <section className="kb-how kb-container"><div><span className="kasa-kicker">SIMPLE FOR THE CALLER. CONNECTED TO YOUR BUSINESS.</span><h2>One call.<br/><span>A better way forward.</span></h2></div><div className="kb-steps">{[['01','Call or request a callback','Use a normal phone call or a short USSD menu. No app or mobile internet on the customer’s device.'],['02','Speak. Be understood.','Choose a familiar language and explain the problem. Kasa retrieves information from your approved knowledge base.'],['03','Get guidance. Keep the context.','Answer supported questions, use authorised integrations, or prepare a human handoff with consent.']].map(([n,title,text])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="kasa-demo-section" id="kasa-demo"><div className="wrap"><header className="kasa-section-heading"><div><span className="kasa-kicker">TRY KASA FOR YOURSELF</span><h2>Less explaining.<br/><em>More understanding.</em></h2></div><p>Explore a working browser demo. Choose a language, start a simulated call, and see the exact knowledge source behind each supported answer.</p></header>
      <div className="kasa-demo-layout"><div className="kasa-console"><div className="kasa-console-top"><strong>Kasa AI</strong><span><i/>{connected?'Demo session active':'Interactive demo'}</span></div><div className="kasa-controls"><label>Conversation language<select value={language} onChange={e=>{reset();setLanguage(e.target.value);}}>{Object.entries(languages).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><fieldset><legend>How you connect</legend><button aria-pressed={channel==='voice'} onClick={()=>{reset();setChannel('voice');}}>Voice call</button><button aria-pressed={channel==='ussd'} onClick={()=>{reset();setChannel('ussd');}}>USSD callback</button></fieldset></div>
      {!connected?<div className="kasa-start"><Phone size={32}/><h3>{channel==='voice'?'A familiar voice is one call away.':'A short menu. Then a voice.'}</h3><p>{channel==='voice'?'In a deployment, dial your provider’s support number and speak in your language.':'In a deployment, a USSD menu lets you request a callback. The conversation continues by voice.'}</p>{channel==='ussd'&&<div className="kasa-ussd">Kasa AI support<br/>1. Request a callback<br/>0. Exit</div>}<button className="kasa-button" onClick={start}>{channel==='voice'?'Start demo call':'1 · Simulate callback'} <Phone size={16}/></button><small>Simulation only. No phone number or mobile account is connected.</small></div>:<><div className="kasa-transcript" role="log" aria-label="Conversation transcript" aria-live="polite">{messages.map((m,i)=><div key={i} className={m.role==='You'?'kasa-message caller':'kasa-message'}><small>{m.role}</small><p>{m.text}</p></div>)}</div><div className="kasa-prompts">{questions[language].map((q,i)=><button key={q} onClick={()=>ask(q)} title={q}>{labels[i]} <ArrowUpRight size={12}/></button>)}</div><form className="kasa-question" onSubmit={e=>{e.preventDefault();ask(question);}}><label htmlFor="kasa-question">Or type a support question</label><div><input id="kasa-question" value={question} maxLength={500} placeholder="Ask about data, airtime, or human support…" onChange={e=>setQuestion(e.target.value)}/><button type="submit" disabled={!question.trim()} aria-label="Send question"><ArrowRight size={20}/></button></div></form><div className="kasa-session-actions"><button onClick={listen}><Volume2 size={15}/> English audio preview</button><button onClick={reset}><PhoneOff size={15}/> End call</button></div>{audioNote&&<p className="kasa-small" role="status">{audioNote}</p>}</>}
      </div><aside className="kasa-evidence"><span className="kasa-kicker">BEHIND THE CONVERSATION</span><h3>Answers with<br/><em>something behind them.</em></h3><ol className="kasa-flow"><li><b>01</b><div><strong>Understand the request</strong><p>Recognise the caller’s language and support need.</p></div></li><li><b>02</b><div><strong>Find the approved answer</strong><p>Retrieve relevant information from the organisation’s knowledge base.</p></div></li><li><b>03</b><div><strong>Reply—or bring in a person</strong><p>Use a supported answer. Escalate when the source is missing or the issue needs a human.</p></div></li></ol><div className="kasa-source" aria-live="polite"><span className="kasa-kicker">{result?'RETRIEVAL RESULT':'WAITING FOR YOUR QUESTION'}</span>{result?<><h4>{result.source?.title||'No supported answer'}</h4><p>{result.source?`${result.source.id} · ${result.source.section}`:result.reason}</p><span className="kasa-status">{result.handoff?'Human support suggested':'Answer found in demo knowledge base'}</span>{language!=='en'&&<details><summary>English meaning</summary><p>{result.english}</p></details>}</>:<p>Ask a question to inspect its source. Try the weather question to see Kasa decline an unsupported answer.</p>}</div>{result?.handoff&&<div className="kasa-handoff"><label><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);setSummary(false);}}/> Include this conversation in the demo handoff summary</label><button className="kasa-button" disabled={!consent} onClick={()=>setSummary(true)}>Preview handoff</button>{summary&&<div role="status"><strong>Demo handoff prepared</strong><p>Language: {languages[language]} · Channel: {channel==='voice'?'Voice call':'USSD callback'}</p><p>Latest question: {messages.filter(m=>m.role==='You').at(-1)?.text}</p><p>Reason: {result.reason}. Nothing has been sent; no live agent is connected.</p></div>}</div>}<button className="kasa-reset" onClick={reset}><RotateCcw size={14}/> Reset experience</button></aside></div>
      <p className="kasa-demo-note">Interactive simulation using sample policies and illustrative translations. Live calling, native-speaker validation and business-system integrations are required for a customer pilot.</p>
    </div></section>
    <section className="kb-trust kb-container" id="kasa-trust"><div><span className="kasa-kicker">TRUST IS PART OF THE EXPERIENCE.</span><h2>Personal service.<br/><span>Clear boundaries.</span></h2><p>Your customers should feel understood. Your business should stay in control of what the AI knows, says and does.</p><a className="kb-text-link" href={contact}>Discuss your integration & security needs <ArrowUpRight size={16}/></a></div><div className="kb-trust-grid"><article><ShieldCheck/><h3>Your knowledge.<br/>Grounded answers.</h3><p>A RAG architecture built around approved business information, with source checks and escalation when an answer is unsupported.</p></article><article><Users/><h3>Permission before<br/>personalisation.</h3><p>Consent-based context sharing and verified access for account-specific help. The browser demo needs no customer account or phone number.</p></article><article><Signal/><h3>Controlled actions.<br/>Accountable service.</h3><p>Backend foundations include policy checks, scoped tools and audit events. Production security is validated as part of the pilot.</p></article><article><Phone/><h3>Offline access.<br/>Real-world reach.</h3><p>No internet on the caller’s phone. Calls and USSD use the mobile network; intelligence runs on the service side.</p></article></div></section>
    <section className="kb-faq kb-container"><h2>A few things<br/><span>worth knowing.</span></h2><div><details><summary>Can a customer really use Kasa without internet?</summary><p>Yes—the service design uses ordinary voice calls or USSD, so the caller does not need mobile data, Wi-Fi or an app. Cellular coverage is still required. The provider operates the telephony and AI infrastructure.</p></details><details><summary>What can we try today?</summary><p>The interactive demo above provides multilingual sample answers, local retrieval, visible sources and a consent-based handoff preview. A live pilot requires an authorised number or shortcode, approved business knowledge, validated speech models and tested integrations.</p></details><details><summary>How does Kasa protect answer quality and customer data?</summary><p>Retrieval grounds answers in approved content, while unsupported questions are escalated. RAG reduces unsupported answers; it does not guarantee zero hallucinations. Live deployments require authenticated telephony, verified account access, encryption, retention controls and security testing. The text demo keeps questions in page memory and sends nothing to a support server.</p></details><details><summary>Can we start with one customer journey?</summary><p>Yes. Start with one language and a high-volume support need. Agree on the approved answers, integration boundaries and human handoff, then measure resolution, repeat contacts, language quality and customer experience.</p></details></div></section>
    <section className="kb-cta" id="contact"><div className="kb-container"><span className="kasa-kicker">YOUR CUSTOMERS ARE CALLING.</span><h2>Make the next<br/>“hello” <span>count.</span></h2><p>Let’s build a support experience that respects their time,<br/>speaks their language, and gives your team room to breathe.</p><a className="kasa-button" href={contact}>Let’s talk about your customer care <ArrowUpRight size={19}/></a><small>Start with a focused pilot. Build around your customers.</small><span className="kb-cta-word" aria-hidden="true">kasa</span></div></section>
    <footer className="kb-footer kb-container"><a href="#" className="kb-brand"><span className="kb-logo" aria-hidden="true"><i/><i/><i/><i/></span>kasa<span className="kb-ai">AI</span></a><p>Good support. In your own language.</p><a href={contact}>Contact Jabess <ArrowUpRight size={14}/></a><Link to="/">Jabess Omane’s portfolio ↗</Link><div className="kb-footer-note">© {new Date().getFullYear()} Kasa AI · Built by Jabess Omane, Ghana.<span>Scenarios are illustrative, not customer results or claims about named providers.</span></div></footer>
  </div>;
}
